name: Kaza
version: v0.1.3
slug: kaza
description: Kaza is a web-based, self-hosted solution for comprehensive household management. Organize your life with features like budgeting, meal planning, recipe management, inventory tracking, shopping lists, and chore scheduling. Keep everything under control while maintaining your privacy with this efficient and customizable tool for your home.
url: https://github.com/juli3nk/kaza
arch:
- amd64
- aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8514
apparmor: false
panel_icon: mdi:home-outline
panel_title: Kaza
panel_admin: false
uart: false
init: false
advanced: false
stage: stable
image: ghcr.io/juli3nk/kaza
tmpfs: true
